# VSCode の拡張機能を入れる。入っているものは飛ばされるので何度実行してもよい。
code --install-extension adpyke.vscode-sql-formatter
code --install-extension anthropic.claude-code
code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension asvetliakov.vscode-neovim
code --install-extension chukwuamaka.csvtojson-converter
code --install-extension codezombiech.gitignore
code --install-extension dustypomerleau.rust-syntax
code --install-extension eamodio.gitlens
code --install-extension golang.go
code --install-extension inferrinizzard.prettier-sql-vscode
code --install-extension janisdd.vscode-edit-csv
code --install-extension long-kudo.vscode-claude-status
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension qufiwefefwoyn.kanagawa
code --install-extension rust-lang.rust-analyzer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tamasfe.even-better-toml
code --install-extension yzane.markdown-pdf
