winget install --id wez.wezterm -e
winget install --id Neovim.Neovim -e
winget install --id Microsoft.PowerShell -e
winget install --id BurntSushi.ripgrep.MSVC -e
winget install --id DEVCOM.JetBrainsMonoNerdFont -e
winget install --id Git.Git -e
winget install --id GitHub.cli -e
winget install --id x-motemen.ghq -e
winget install --id OpenJS.NodeJS.LTS -e
winget install --id ajeetdsouza.zoxide -e
