winget install --id wez.wezterm -e
winget install --id Neovim.Neovim -e
winget install --id Microsoft.PowerShell -e
winget install --id BurntSushi.ripgrep.MSVC -e
winget install --id DEVCOM.JetBrainsMonoNerdFont -e
winget install --id Git.Git -e
winget install --id GitHub.cli -e
winget install --id x-motemen.ghq -e
winget install --id OpenJS.NodeJS.LTS -e
winget install --id pnpm.pnpm -e
winget install --id ajeetdsouza.zoxide -e
winget install --id junegunn.fzf -e
winget install --id Microsoft.VisualStudio.2022.BuildTools -e --override "--quiet --wait --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
winget install --id Microsoft.PowerToys -e
winget install --id JanDeDobbeleer.OhMyPosh -e
winget install --id JohnMacFarlane.Pandoc -e
winget install --id Gyan.FFmpeg -e
winget install --id Zen-Team.Zen-Browser -e
winget install --id sakura-editor.sakura -e
winget install --id qutebrowser.qutebrowser -e
winget install --id astral-sh.uv -e
winget install --id gopass.gopass -e
winget install --id FiloSottile.age -e
winget install --id TortoiseGit.TortoiseGit -e
winget install --id aloneguid.bt -e
